apiVersion: v1
kind: Service
metadata:
  name: faas-netes
  namespace: openfaas
  labels:
    app: faas-netes
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: gateway
