apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gateway
  namespace: openfaas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      serviceAccountName: faas-controller
      containers:
      - name: gateway
        image: openfaas/gateway:0.8.8
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 10
          timeoutSeconds: 2

        env:
        - name: functions_provider_url
          value: "http://127.0.0.1:8081/" # Final `.` specifies an absolute address
        - name: faas_nats_address
          value: "nats.openfaas.svc.cluster.local."
        - name: faas_nats_port
          value: "4222"
        - name: direct_functions
          value: "true"                             # Functions are invoked directly over the overlay network
        - name: direct_functions_suffix
          value: "openfaas-fn.svc.cluster.local."   # contains K8s namespace
        - name: read_timeout
          value: "35s"
        - name: write_timeout
          value: "35s"
        - name: upstream_timeout  # Must be smaller than read/write_timeout
          value: "30s"
        - name: basic_auth
          value: "false"
        - name: secret_mount_path
          value: "/etc/openfaas"
        - name: scale_from_zero
          value: "false"

        ports:
        - containerPort: 8080
          protocol: TCP

        resources:
          requests:
            memory: 250Mi
          limits:
            memory: 250Mi   # Adjust to suit needs of deployment

      - name: faas-netes
        image: openfaas/faas-netes:0.5.7
        imagePullPolicy: Always
        env:
        - name: port
          value: "8081"
        - name: function_namespace
          value: openfaas-fn
        - name: read_timeout
          value: "10"
        - name: write_timeout
          value: "10"
        ports:
        - containerPort: 8081
          protocol: TCP
