---
- name: SSHD Security Configuration
  serial: '{{ serial | default(1) }}'
  hosts: "{{ hosts }}"
  become: false

  tasks:
    - name: Airflow | Create name spcace
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: airflow

    - name: Airflow | Deployment
      k8s:
        state: present
        definition:
          apiVersion: extensions/v1beta1
          kind: Deployment
          metadata:
            name: airflow
            namespace: airflow
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: airflow
            template:
              metadata:
                labels:
                  app: airflow
              spec:
                containers:
                - name: airflow
                  image: puckel/docker-airflow
                  ports:
                  - containerPort: 8080
                    protocol: TCP
                    name: http

    - name: Airflow | Set Service
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: airflow-svc
            namespace: airflow
          spec:
            selector:
              app: airflow
            ports:
            - name: http
              protocol: TCP
              port: 80
              targetPort: 8080

    - name: Airflow | Set Ingress
      k8s:
        state: present
        definition:
          apiVersion: extensions/v1beta1
          kind: Ingress
          metadata:
            name: airflow-ingress
            namespace: airflow
            labels:
              k8s-app: airflow
            annotations:
              kubernetes.io/ingress.class: traefik
              traefik.ingress.kubernetes.io/frontend-entry-points: http
          spec:
            rules:
            - host: airflow.localhost
              http:
                paths:
                - backend:
                    serviceName: airflow-svc
                    servicePort: 80
