---
kind: ConfigMap
apiVersion: v1
metadata:
 name: traefik
 namespace: ingress-traefik
data:
 traefik-config: |-
   InsecureSkipVerify = true
   [entryPoints]
     [entryPoints.http]
     address = ":80"
     [entryPoints.https]
     address = ":443"
      [entryPoints.https.tls]
        [[entryPoints.https.tls.certificates]]
        certFile = "/ssl/localhost.tls.crt"
        keyFile = "/ssl/localhost.tls.key"