functionNamespace: openfaas-fn

async: true

exposeServices: false
serviceType: ClusterIP
rbac: true
securityContext: true
basic_auth: false

faasnetesd:
  image: openfaas/faas-netes:0.7.0
  readTimeout : "60s"
  writeTimeout : "60s"
  imagePullPolicy : "IfNotPresent"    # Image pull policy for deployed functions
  httpProbe: false              # Setting to true will use a lock file for readiness and liveness (incompatible with Istio)
  readinessProbe:
    initialDelaySeconds: 0
    timeoutSeconds: 1           # Tuned-in to run checks early and quickly to support fast cold-start from zero replicas
    periodSeconds: 1
  livenessProbe:
    initialDelaySeconds: 3
    timeoutSeconds: 1
    periodSeconds: 10

gateway:
  image: openfaas/gateway:0.9.14
  readTimeout : "65s"
  writeTimeout : "65s"
  upstreamTimeout : "60s"  # Must be smaller than read/write_timeout
  replicas: 1
  scaleFromZero: true
  # change the port when creating multiple releases in the same baremetal cluster
  nodePort: 31112

queueWorker:
  image: openfaas/queue-worker:0.5.4
  ackWait : "60s"
  replicas: 1

# image pull policy for openfaas components, can change to `IfNotPresent` in offline env
openfaasImagePullPolicy: "IfNotPresent"

# replaces faas-netes with openfaas-operator
operator:
  image: openfaas/openfaas-operator:0.9.1
  create: false
  # set this to false when creating multiple releases in the same cluster
  # must be true for the first one only
  createCRD: true

# monitoring and auto-scaling components
prometheus:
  image: prom/prometheus:v2.3.1
alertmanager:
  image: prom/alertmanager:v0.15.0

# async provider
nats:
  image: nats-streaming:0.11.2
  enableMonitoring: false

# ingress configuration
ingress:
  enabled: true
  # Used to create Ingress record (should be used with exposeServices: false).
  hosts:
    - host: openfaas.localhost
      serviceName: gateway
      servicePort: 8080
      path: /
  annotations:
    kubernetes.io/ingress.class: traefik
  tls:
    # Secrets must be manually created in the namespace.

# faas-idler configuration
faasIdler:
  replicas: 1
  image: openfaas/faas-idler:0.1.9
  inactivityDuration: 5m
  reconcileInterval: 30s
  dryRun: true                          # Set to true to enable the idler to apply changes and scale to zero

nodeSelector: {}

tolerations: []

affinity: {}

kubernetesDNSDomain: cluster.local
